export const KEYCLOAK_URL = process.env.NEXT_PUBLIC_KEYCLOAK_URL;
export const KEYCLOAK_REALM = process.env.NEXT_PUBLIC_KEYCLOAK_REALM;
export const KEYCLOAK_CLIENT_ID = process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID;