import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import MainContext from "@/contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eaee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContext>
      <html lang="pt-br">
        <body className={`${inter.className} flex`}>
          <div className="hidden lg:flex min-w-[200px] border-r min-h-screen">
            <Sidebar />
          </div>

          <main className="flex flex-col h-screen w-screen">
            <Header />
            {children}
          </main>
        </body>
      </html>
    </MainContext>
  );
}
